version: '3.8.0'
name: 'web-scrape-app'
services:

  mysql_srvc:
    build:
      context: ./mysql_image
      dockerfile: Dockerfile
    container_name: sel-mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql #Datebase storage

  chrome1_srvc:
    build:
      context: ./chrome_image
      dockerfile: Dockerfile
    container_name: sel-chrome1
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SEL_DOWNLOAD_DIR=/home/seluser/Downloads
    env_file:
      - .env
    #ports:
    #  - 7900:7900 # Expose noVNC port 7900 for debugging if needed
    volumes:
      - chrome-data1:/home/seluser/.config/google-chrome #chrome profile and site cookies
      - shared-files:/home/seluser/Downloads:z  #Shared folder 

  chrome2_srvc:
    build:
      context: ./chrome_image
      dockerfile: Dockerfile
    container_name: sel-chrome2
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SEL_DOWNLOAD_DIR=/home/seluser/Downloads
    env_file:
      - .env
    #ports:
    #  - 7900:7900 # Expose noVNC port 7900 for debugging if needed
    volumes:
      - chrome-data2:/home/seluser/.config/google-chrome #chrome profile and site cookies
      - shared-files:/home/seluser/Downloads:z  #Shared folder 

  chrome3_srvc:
    build:
      context: ./chrome_image
      dockerfile: Dockerfile
    container_name: sel-chrome3
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SEL_DOWNLOAD_DIR=/home/seluser/Downloads
    env_file:
      - .env
    #ports:
    #  - 7900:7900 # Expose noVNC port 7900 for debugging if needed
    volumes:
      - chrome-data3:/home/seluser/.config/google-chrome #chrome profile and site cookies
      - shared-files:/home/seluser/Downloads:z  #Shared folder      

  chrome4_srvc:
    build:
      context: ./chrome_image
      dockerfile: Dockerfile
    container_name: sel-chrome4
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SEL_DOWNLOAD_DIR=/home/seluser/Downloads
    env_file:
      - .env
    #ports:
    #  - 7900:7900 # Expose noVNC port 7900 for debugging if needed
    volumes:
      - chrome-data4:/home/seluser/.config/google-chrome #chrome profile and site cookies
      - shared-files:/home/seluser/Downloads:z  #Shared folder 

  php_srvc:
    build:
      context: ./php_image
      dockerfile: Dockerfile
    container_name: sel-php
    env_file:
      - .env
    #ports:
    #  - 85:80 # Expose HTTP port 80 if needed
    volumes:
      - shared-files:/var/www/html/filesfolder:z  #Shared folder 

volumes:
  mysql-data:
    driver: local
  shared-files:
    driver: local

  chrome-data1:
    driver: local
  chrome-data2:
    driver: local
  chrome-data3:
    driver: local
  chrome-data4:
    driver: local